//! Build script that generates the IANA IPFIX Information Element registry
//! from the vendored CSV at `assets/iana/ipfix-information-elements.csv`.
//!
//! The output is written to `$OUT_DIR/ie_generated.rs` and included by
//! `src/ie/mod.rs`. It contains a single sorted slice of element records, so
//! the runtime lookup is a `binary_search_by_key`.
//!
//! No external dependencies are used; the CSV parser below is a small,
//! purpose-built state machine that handles RFC 4180-style quoting (including
//! `""` escapes and embedded newlines/commas inside quoted fields).

use heck::ToShoutySnakeCase;
use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

const CSV_PATH: &str = "assets/iana/ipfix-information-elements.csv";

fn main() {
    println!("cargo:rerun-if-changed={CSV_PATH}");
    println!("cargo:rerun-if-changed=build.rs");

    let csv = fs::read_to_string(CSV_PATH).expect("read IANA IE CSV");
    let rows = parse_csv(&csv);

    // Header row is row 0; skip it. Required columns:
    //   0 ElementID, 1 Name, 2 Abstract Data Type, 3 Data Type Semantics,
    //   4 Status
    let mut elements: Vec<Element> = Vec::new();
    for row in rows.iter().skip(1) {
        if row.len() < 5 {
            continue;
        }
        let id_field = row[0].trim();
        let name = row[1].trim();
        let dtype = row[2].trim();
        let semantic = row[3].trim();
        let status = row[4].trim();

        // Skip placeholders ("Reserved", "Assigned for ...", ranges like
        // "35-40"), entries without a usable abstract data type, and
        // anything not marked "current".
        if name.is_empty() || dtype.is_empty() {
            continue;
        }
        if !status.eq_ignore_ascii_case("current") {
            continue;
        }
        let Ok(id) = id_field.parse::<u16>() else {
            continue;
        };
        let Some(dt_variant) = data_type_variant(dtype) else {
            // Skip unknown abstract data types (e.g. "unsigned256").
            continue;
        };
        let sem_variant = semantic_variant(semantic);

        elements.push(Element {
            id,
            name: name.to_string(),
            data_type: dt_variant,
            semantic: sem_variant,
        });
    }

    elements.sort_by_key(|e| e.id);
    elements.dedup_by_key(|e| e.id);

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("ie_generated.rs");
    let mut f = fs::File::create(&out_path).expect("create generated.rs");

    writeln!(
        f,
        "// @generated by build.rs from assets/iana/ipfix-information-elements.csv\n\
         // DO NOT EDIT.\n\
         \n\
         pub(crate) static REGISTRY: &[InfoElement] = &["
    )
    .expect("write");
    for e in &elements {
        let sem = match e.semantic {
            Some(s) => format!("Some(Semantic::{s})"),
            None => "None".to_string(),
        };
        writeln!(
            f,
            "    InfoElement {{ id: {}, name: {:?}, data_type: DataType::{}, semantic: {} }},",
            e.id, e.name, e.data_type, sem,
        )
        .expect("write");
    }
    writeln!(f, "];").expect("write");

    // Per-IE numeric ID constants. Lets callers write
    // `ipfix_parser::ie::id::OCTET_DELTA_COUNT` instead of copying the
    // raw `1u16` out of the IANA registry. Names are SCREAMING_SNAKE_CASE
    // conversions of the IANA camelCase names; see `screaming_snake`
    // below for the exact mapping rule.
    writeln!(
        f,
        "\n\
         /// Numeric IDs of every IANA-allocated Information Element known\n\
         /// to this crate, as `pub const u16`s.\n\
         ///\n\
         /// Names are mechanical `SCREAMING_SNAKE_CASE` conversions of\n\
         /// the IANA registry names (e.g. `octetDeltaCount` →\n\
         /// `OCTET_DELTA_COUNT`, `sourceIPv4Address` →\n\
         /// `SOURCE_IPV4_ADDRESS`). Generated from the vendored CSV at\n\
         /// build time.\n\
         pub mod id {{"
    )
    .expect("write");
    let mut seen_names = std::collections::HashSet::new();
    for e in &elements {
        // `heck` splits on every uppercase letter, so `IPv4` becomes
        // `I` + `Pv4` and produces `I_PV4` instead of `IPV4`. Normalize
        // the IANA acronyms so each becomes a single camel-case word.
        let normalized = e.name.replace("IPv4", "Ipv4").replace("IPv6", "Ipv6");
        let mut name = normalized.to_shouty_snake_case();
        // Defensive: if two IANA entries collide once normalized, suffix
        // the second with its numeric ID to keep the module compiling.
        if !seen_names.insert(name.clone()) {
            name = format!("{name}_{}", e.id);
        }
        writeln!(
            f,
            "    /// `{}` (IE {}).\n    pub const {}: u16 = {};",
            e.name, e.id, name, e.id,
        )
        .expect("write");
    }
    writeln!(f, "}}").expect("write");
}

struct Element {
    id: u16,
    name: String,
    data_type: &'static str,
    semantic: Option<&'static str>,
}

fn data_type_variant(s: &str) -> Option<&'static str> {
    Some(match s {
        "octetArray" => "OctetArray",
        "unsigned8" => "Unsigned8",
        "unsigned16" => "Unsigned16",
        "unsigned32" => "Unsigned32",
        "unsigned64" => "Unsigned64",
        "signed8" => "Signed8",
        "signed16" => "Signed16",
        "signed32" => "Signed32",
        "signed64" => "Signed64",
        "float32" => "Float32",
        "float64" => "Float64",
        "boolean" => "Boolean",
        "macAddress" => "MacAddress",
        "string" => "String",
        "dateTimeSeconds" => "DateTimeSeconds",
        "dateTimeMilliseconds" => "DateTimeMilliseconds",
        "dateTimeMicroseconds" => "DateTimeMicroseconds",
        "dateTimeNanoseconds" => "DateTimeNanoseconds",
        "ipv4Address" => "Ipv4Address",
        "ipv6Address" => "Ipv6Address",
        "basicList" => "BasicList",
        "subTemplateList" => "SubTemplateList",
        "subTemplateMultiList" => "SubTemplateMultiList",
        _ => return None,
    })
}

fn semantic_variant(s: &str) -> Option<&'static str> {
    Some(match s {
        "default" => "Default",
        "quantity" => "Quantity",
        "totalCounter" => "TotalCounter",
        "deltaCounter" => "DeltaCounter",
        "identifier" => "Identifier",
        "flags" => "Flags",
        "list" => "List",
        "snmpCounter" => "SnmpCounter",
        "snmpGauge" => "SnmpGauge",
        _ => return None,
    })
}

/// Minimal RFC-4180-style CSV parser. Handles quoted fields, embedded commas,
/// embedded newlines, and `""` quote escapes. Recognizes both `\n` and
/// `\r\n` row terminators.
fn parse_csv(input: &str) -> Vec<Vec<String>> {
    let mut rows: Vec<Vec<String>> = Vec::new();
    let mut row: Vec<String> = Vec::new();
    let mut field = String::new();
    let mut in_quotes = false;
    let mut chars = input.chars().peekable();

    while let Some(c) = chars.next() {
        if in_quotes {
            if c == '"' {
                if chars.peek() == Some(&'"') {
                    chars.next();
                    field.push('"');
                } else {
                    in_quotes = false;
                }
            } else {
                field.push(c);
            }
        } else {
            match c {
                '"' => in_quotes = true,
                ',' => {
                    let f = std::mem::take(&mut field);
                    row.push(f);
                }
                '\r' => {
                    if chars.peek() == Some(&'\n') {
                        chars.next();
                    }
                    row.push(std::mem::take(&mut field));
                    rows.push(std::mem::take(&mut row));
                }
                '\n' => {
                    row.push(std::mem::take(&mut field));
                    rows.push(std::mem::take(&mut row));
                }
                _ => field.push(c),
            }
        }
    }
    if !field.is_empty() || !row.is_empty() {
        row.push(field);
        rows.push(row);
    }
    rows
}
